const data = [
  [
    "1",
    "Fila 1 - Columna 2",
    "Fila 1 - Columna 3",
    "Fila 1 - Columna 4",
    "Fila 1 - Columna 5",
    "Fila 1 - Columna 6",
    "Fila 1 - pagina 1 7",
    "Fila 2 - pagina 1 8",
    "Fila 2 - Columna 8Lorem ipsum dolor",
    "Fila 2 - Columna 8Lorem ipsum dolor",
  ],
  [
    "2",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
    "Fila 2 - Columna 8Lorem ipsum dolor",
    "Fila 2 - Columna 8Lorem ipsum dolor",
  ],
  [
    "3",
    "Fila 1 - Columna 2",
    "Fila 1 - Columna 3",
    "Fila 1 - Columna 4",
    "Fila 1 - Columna 5",
    "Fila 1 - Columna 6",
    "Fila 1 - Columna 7",
    "Fila 2 - Columna 8",
    "Fila 2 - Columna 8Lorem ipsum dolor",
    "Fila 2 - Columna 8Lorem ipsum dolor",
  ],
  [
    "4",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
    "Fila 2 - Columna 8Lorem ipsum dolor",
    "Fila 2 - Columna 8Lorem ipsum dolor",
  ],
  [
    "5",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "<img src='casa5.jpg'>",
    "Fila 2 - Columna 8Lorem ipsum dolor",
    "Fila 2 - Columna final",
  ],
  [
    "6",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Datos pagina 2",
    "Fila 2 - Columna 8Lorem ipsum dolor",
    "Fila 2 - Columna 8Lorem ipsum dolor",,
  ],
  [
    "7",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
    "Fila 2 - Columna 8Lorem ipsum dolor",
    "Fila 2 - Columna 8Lorem ipsum dolor",
  ],
  [
    "8",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
    "Fila 2 - Columna 8Lorem ipsum dolor",
    "Fila 2 - Columna 8Lorem ipsum dolor",
  ],
  [
    "9",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "<img src='casa5.jpg'>",
    "Fila 2 - Columna 8",
    "Fila 2 - Columna 8Lorem ipsum dolor",
    "Fila 2 - Columna 8Lorem ipsum dolor",
  ],
  [
    "10",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
    "Fila 2 - Columna 8Lorem ipsum dolor",
    "Fila 2 - Columna 8Lorem ipsum dolor",
  ],
  [
    "11",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
    "Fila 2 - Columna 8Lorem ipsum dolor",
    "Fila 2 - Columna 8Lorem ipsum dolor",
  ],
  [
    "12",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
    "Fila 2 - Columna 8Lorem ipsum dolor",
    "Fila 2 - Columna 8Lorem ipsum dolor",
  ],
  [
    "13",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
    "Fila 2 - Columna 8Lorem ipsum dolor",
    "Fila 2 - Columna 8Lorem ipsum dolor",
  ],
  [
    "14",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
    "Fila 2 - Columna 8Lorem ipsum dolor",
    "Fila 2 - Columna 8Lorem ipsum dolor",
  ],
  [
    "15",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
    "Fila 2 - Columna 8Lorem ipsum dolor",
    "Fila 2 - Columna 8Lorem ipsum dolor",
  ],
  [
    "16",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
    "Fila 2 - Columna 8Lorem ipsum dolor",
    "Fila 2 - Columna 8Lorem ipsum dolor",
  ],
]

new TableUI('myTable')
  .create({
    data,
    totalRows: 0,
    btnPreview: "Anterior",
    btnNext:"Siguiente",
    /*query: (perPage, currentPage) => {
      const init = (perPage * (currentPage - 1)) + 1
      const end = init + (perPage - 1)
      return data.slice((init - 1), end)
    }*/
  })
