const data = [
  [
    "1",
    "Fila 1 - Columna 2",
    "Fila 1 - Columna 3",
    "Fila 1 - Columna 4",
    "Fila 1 - Columna 5",
    "Fila 1 - Columna 6",
    "Fila 1 - Columna 7",
    "<button>Editar</button><button>Borrar</button>",
  ],
  [
    "2",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
  ],
  [
    "1",
    "Fila 1 - Columna 2",
    "Fila 1 - Columna 3",
    "Fila 1 - Columna 4",
    "Fila 1 - Columna 5",
    "Fila 1 - Columna 6",
    "Fila 1 - Columna 7",
    "<button>Editar</button><button>Borrar</button>",
  ],
  [
    "2",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
  ],
  [
    "2",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
  ],
  [
    "2",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
  ],
  [
    "2",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
  ],
  [
    "2",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
  ],
  [
    "2",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
  ],
  [
    "2",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
  ],
  [
    "2",
    "Fila 2 - Columna 2",
    "Fila 2 - Columna 3",
    "Fila 2 - Columna 4",
    "Fila 2 - Columna 5",
    "Fila 2 - Columna 6",
    "Fila 2 - Columna 7",
    "Fila 2 - Columna 8",
  ],
]

new TableUI('myTable').create({
  data
})
